### ISSUE TITLE
Islamic provinces outside CK3 - what if Islam is wiped out

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/CK3toEU4#153]
See /configurables/no_islam_overrides.txt

**Comment by Elfangor567** [comment]
Hindu also appears outside of CK3 scope in the Indonesia/Malaysia area. Would we eliminate that too? I'm not sure this is a good idea unless it's an Imperator save or some such.

**Comment by IohannesIohannium** [comment]
No, no, all the provinces listed in that file are Sunni or Ibadi in EU4 Vanilla. The *replacements* are usually Hindu or Animist.

**Comment by Elfangor567** [comment]
Ah, it's for IR save conversions. That makes more sense. The phrasing of the issue had me think it was for if Islam died out in CK3 in general.
