### ISSUE TITLE
Interesting inheritance cases to consider

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/CK3toEU4#158]
- [ ] PU Jure Uxoris: the ruler of country A is married to the ruler of country B.
  - If any of the two dies: force the other country into a junior union
- [ ] Already ruling: the heir of country A is the ruler of country B.
  - If the ruler of country A dies: put country A in a junior union with country B
  - If the ruler of country B dies: kill the heir in country A
  - If the heir of country A dies: kill the ruler of country B
- [ ] Shared heir: country A and country B, ruled by different people, share the same heir.
  - If any of the two ruler dies: refer to the "Already ruling" scenario
  - If the heir dies in any of the two country: kill the heir of the other country
- [ ] In-law times: the ruler of country A is the married to the heir of country B.
  - If country A's consort dies: kill country B's heir
  - If country B's heir dies: kill country A's consort
  - If country A leader dies: situation is already solved
  - If country B leader dies: refer to the "PU Jure Uxoris" scenario

Precedence rules for deciding the senior partner in a union:
- Rank difference
- Development size

**Comment by cetvrtak** [comment]
Just a tiny addition - if an heir is inheriting his CK3 overlord, then the overlord's title becomes senior in a union.

**Comment by Elfangor567** [comment]
Considering the precedent with the Iberian Wedding, perhaps for marriages we should just have the ruling dynasty become the leader of a PU. (The husband for patrilineal marriages, and the wife for matrilineal marriages) we should also make sure that they either share an heir or are both childless.

**Comment by Zemurin** [comment]
All of these are interesting and make sense on paper. Unfortunately:
a) This would require an event, and doesn't extend past conversion date.
b) EU4 can't recognize the heir of A is ruler of B. they are different people as there is no way to link them.
c) same as B. Only instance of a shared heir is an already established PU.
d) would require events for this, and again, only would apply for countries at start date.

**Comment by Zemurin** [comment]
After considering, I'm not really in favor of doing this. I;ve been reading up on vanilla EU4 errors where heir of A is ruler of B and EU4 still considers them different persons due to lacking events that would link up both titles on death of A ruler.

EU4 just isn't geared for this type of relationship detail, and I'm not really in favor of writing events dynamically for this - those are prone to degradation as the game changes mod support over versions.

I'll be closing for now.
