### ISSUE TITLE
Coat of arms into image files

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/CK3toEU4#172]
A program could be created that turns all scripted CK3 coat of arms into tga files, while still retaining the original names.

E.g.: if we have the following entry:

```
two_emblems_scaled_and_positioned = {
    pattern = "pattern_vertical_split_01"
    color1 = "lemon_yellow"
    color2 = "sky_blue"
 
    textured_emblem = {
        texture = "te_griffin_01"
        instance = { position = { 0.75 0.75 } scale = { 0.5 0.5 }  }
        instance = { position = { 0.75 0.25 } scale = { 0.5 0.5 }  }
    }
}
```

...a file named _two_emblems_scaled_and_positioned.tga_, size 128 x 128 pixel, should be output and look like this:

![image](https://user-images.githubusercontent.com/24550392/114475213-1d422180-9bf8-11eb-9db8-3bdddfdf49da.png)

Such a program would do this process to all coat of arms defined in /common/coat_of_arms/coat_of_arms/01_landed_titles.txt

**Comment by Zemurin** [comment]
Done by GOLExtractor.
