### ISSUE TITLE
Opening religon tab cause CTD when using Reformed Religion/Custom heresy created in CK3

### ISSUE THREAD

**Issue by Finley-Williams** [ParadoxGameConverters/CK3toEU4#176]
[fixedwindow.cpp:2951]: interface/added_countryreligionview.gui: Missing Icon 'defender_of_the_faith_tier' in window 'countryreligionview'.

Any custom religion seems to do it.

Version: 0.7 Gayomarthian
EU4 Version: 1.31 and 1.31.1

**Comment by Zemurin** [comment]
We're aware, thanx. You're operating on an unreleased experimental build.

**Comment by Zemurin** [comment]
Please grab the latest build and see if all is well.

**Comment by Zemurin** [comment]
Should be solved now.
