### ISSUE TITLE
Custom HRE name

### ISSUE THREAD

**Issue by WilhelmStein** [ParadoxGameConverters/CK3toEU4#195]
I noticed that whilst one can hre-ify an empire, the name stays "Holy Roman Empire" instead of changing dynamically.
Is the name "HRE" something bound to a variable or is it hardcoded in events and other places, rendering such change inconsistent in places, making such a request kind of moot?

**Comment by Elfangor567** [comment]
It's possible. You would need to change A LOT of localization though. I looked into but deemed it too much work for too little return. If you want to though, I fully support it.

**Comment by Zemurin** [comment]
Not viable, unfortunately. This isn't just changing HRE: and HRE_ADJ:, it's systematic changing of tons of locs across languages and grammars. I don't think thsi is worth the effort.
