### ISSUE TITLE
Province mapping ck3 = 8782 is invalid. We cannot find related county.

### ISSUE THREAD

**Issue by Asmodaus** [ParadoxGameConverters/CK3toEU4#202]
Province mapping ck3 = 8782 is invalid. We cannot find related county.

I have used conertor-mod after playing Imperator Rome

**Comment by Asmodaus** [comment]
[configuration.txt](https://github.com/ParadoxGameConverters/CK3toEU4/files/6570450/configuration.txt)
[log.txt](https://github.com/ParadoxGameConverters/CK3toEU4/files/6570451/log.txt)

Log and configuration is here

**Comment by Zemurin** [comment]
[code]
* Compatible with CK3 1.3 and EU4 1.31
...
2021-05-31 16:05:32     [INFO] <> Savegame version: 1.1.3
[/code]
PEBKAC
