### ISSUE TITLE
County c_kintus has culture 4294967295 which has no definition!

### ISSUE THREAD

**Issue by Asmodaus** [ParadoxGameConverters/CK3toEU4#203]
County c_kintus has culture 4294967295 which has no definition!

**Comment by Asmodaus** [comment]
[log.txt](https://github.com/ParadoxGameConverters/CK3toEU4/files/6583934/log.txt)
[configuration.txt](https://github.com/ParadoxGameConverters/CK3toEU4/files/6583935/configuration.txt)
[log.txt](https://github.com/ParadoxGameConverters/CK3toEU4/files/6583936/log.txt)

**Comment by Zemurin** [comment]
You started in 1.2 and imported your save into 1.3.
This corrupted your game and you won't be able to convert that save into eu4.
