### ISSUE TITLE
Compatibility with mod "East Asia Reboot"

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/CK3toEU4#238]
See if compatibility with mod _East Asia Reboot_ / _[아시아추가](https://gall.dcinside.com/mgallery/board/view/?id=crusaderkings&no=149906)_ is feasible and how

While the page is in Korean, the mod is an interesting expansion of CK3 to allow for Eastern Asia and also has scenarios up to 1836

**Comment by CarbonY26** [comment]
There's a CK2 counterpart named "Tianxia" too
