### ISSUE TITLE
Change Nestorian holy sites [currently use Coptic holy sites as in PDS' converter]

### ISSUE THREAD

**Issue by TinWiz** [ParadoxGameConverters/CK3toEU4#318]
I have a small suggestion for this converter. Right now Nestorianism uses the Coptic holy sites, like it did in Paradox's own version of the converter. I would suggest changing those sites to historical locations, like the ones from CK2/CK3, plus Xi'an in China. That would be 

holy_sites = { 2308 410 445 535 700 }

 for the file { Urfa Baghdad Merw Kochin Xi'an } . I also posted a zip file with some pics for the holy sites a while back on the forums. https://forum.paradoxplaza.com/forum/threads/nestorian-holy-sites-mod.1160460/#post-26079256 Any chance we can add that to the next version?

**Comment by IohannesIohannium** [comment]
Solved in #319, can be closed
