### ISSUE TITLE
No ideas for default cultures

### ISSUE THREAD

**Issue by dnarik** [ParadoxGameConverters/CK3ToEU4#510]
Currently, it seems like Hybrid and Divergent cultures get unique National Ideas when I am using the converter. I may be mistaken, but there used to be unique national ideas based on traditions for every culture? Perhaps this could be an issue with the save file I am using for conversion, but I donwloaded frech converter and deleted all the previous files, the result is still the same

**Comment by Zemurin** [comment]
Please clarify.
Yes, we generate cultural national ideas for those countries that are created in ck3 timeframe (hybrid + divergent).
Other cultures that merely map to EU4 vanilla ideas retain their EU4 ideas, we don't override those.
Titles that map to EU4 tags that have EU4 ideas keep those instead, but generally vanilla EU4 cultural ideas fill out the rest. Only cultures lacking any cultural idea fallback are precisely custom cultures that we then generate ideas for.

So, what's missing?
