### ISSUE TITLE
Non-1252 chars

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/CK3toEU4#71]
This file is an example of how the "mappings" between non-1252 and 1252 chars should be done

https://pastebin.com/wXah8DRN

See:
```
# link = { utf8 = "utf8 character" win1252 = "win1252 substitute" }
# As an example, ł --> l, hence Płock will become Plock
```

Edit: updated with support for some translations. Still missing Korean and Chinese.
Edit 2: added full support for Korean and Japanese kana and partial support for Chinese characters. Full support for the latter would be impossible without using some converter function.

**Comment by Zemurin** [comment]
This looks good. I can work with this.

**Comment by cxl180** [comment]
Our Asain player uses a plugin to diaplay our letters. A key part of this solution is an encoding conversion tool that transforms UTF-8 into a compatible format. The code for this converter is available here:
https://github.com/matanki-saito/EU4SpecialEscape
